[setup]
statement_files = ["sql/articles.sql", "sql/colors.sql"]
statements = [
    "copy articles from 's3://crate-stresstest-data/join-sample-data/articles_*' with (compression = 'gzip')",
    "copy colors from 's3://crate-stresstest-data/join-sample-data/colors_*' with (compression = 'gzip')",
    "refresh table articles, colors"
]

[[queries]]
statement = "select * from articles inner join colors on articles.id = colors.id order by articles.id limit 1000"
iterations = 50


[teardown]
statements = ["drop table articles", "drop table colors"]
