[setup]
statement_files = ["sql/uservisits_analyzer.sql"]
statements = [
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-00001*' with (compression = 'gzip')",
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-00002*' with (compression = 'gzip')",
    "refresh table uservisits"
]

[[queries]]
statement = '''select * from userVisits where "UserAgent" ~ '(?i).*\bWindows\sNT\s6.0\b.*' limit 10000'''
iterations = 500

[teardown]
statements = ["drop table uservisits"]
