[setup]
statement_files = ["../specs/sql/uservisits.sql"]
statements = [
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/tiny/uservisits/part-00000.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/tiny/uservisits/part-00001.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/tiny/uservisits/part-00002.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/tiny/uservisits/part-00003.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/tiny/uservisits/part-00004.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/tiny/uservisits/part-00005.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/tiny/uservisits/part-00006.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/tiny/uservisits/part-00007.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/tiny/uservisits/part-00008.gz' with (compression = 'gzip')",
    "copy uservisits from 'https://cdn.crate.io/downloads/datasets/amplab/tiny/uservisits/part-00009.gz' with (compression = 'gzip')",
    "refresh table uservisits"
]

[[queries]]
statement = "select 1"
concurrency = 25
iterations = 1000

[[queries]]
statement = "select * from uservisits limit 10"
concurrency = 25
iterations = 1000

[[queries]]
statement = '''select extract(day from "visitDate"), count(*) from uservisits group by 1 order by 2 desc limit 20'''
concurrency = 5
iterations = 500

[teardown]
statements = ["drop table uservisits"]
