[setup]
statement_files = ["sql/uservisits.sql"]
statements = [
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-00001*' with (compression = 'gzip')",
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-00002*' with (compression = 'gzip')",
    "refresh table uservisits"
]

[[queries]]
statement = '''select "sourceIP" from uservisits where "sourceIP" like '%.%.%.%' limit 3000'''
iterations = 200

[[queries]]
statement = '''select "sourceIP" from uservisits where "sourceIP" ilike '%.%.%.%' limit 3000'''
iterations = 200

[[queries]]
statement = '''select "UserAgent" from uservisits where "UserAgent" like 'mozilla%' limit 3000'''
iterations = 200

[[queries]]
statement = '''select "UserAgent" from uservisits where "UserAgent" ilike 'mozilla%' limit 3000'''
iterations = 200

[teardown]
statements = ["drop table uservisits"]
